# apiVersion: v1
# kind: Pod
# metadata: 
#   name: mongo
#   labels:
#     name: mongo
# spec:
#   containers :
#      - resources:
#         limits : 
#          cpu: 0.5
#        image: mongo
#        name: mongo
#        env:
#           - name: MONGO_ROOT_PASSWORD
#             value: netapp01
#        ports:
#           - containerPort: 27017
#             name: mongo
#        volumeMounts: 
#           - name: mongo-persistent-storage
#             mountPath: /var/lib/mongo
#   volumes:
#     - name: mongo-persistent-storage
#       persistentVolumeClaim: 
#        claimName: mongo-disk



apiVersion: v1
kind: Service
metadata: 
  annotations: 
    cloud.google.com/load-balancer-type: Internal
  name: mongo-2
  namespace: mongo
spec: 
  ports: 
    - 
      port: 27019
      targetPort: 27017
  selector: 
    statefulset.kubernetes.io/pod-name: mongo-2
  type: LoadBalancer
